<?php

/**
 * Perú Places
 * @author   Marketing Rapel
 * @version  1.1.26
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */
global $places;

$places['PE'] = array(
	'AMA' => array(
		'Aramango',
		'Asunción',
		'Bagua Grande',
		'Bagua',
		'Balsas',
		'Cajaruro',
		'Camporredondo',
		'Chachapoyas',
		'Cheto',
		'Chiliquín',
		'Chirimoto',
		'Chisquilla',
		'Chuquibamba',
		'Churuja',
		'Cocabamba',
		'Cochamal',
		'Colcamar',
		'Conila',
		'Copallin',
		'Corosha',
		'Cuispes',
		'Cumba',
		'El Cenepa',
		'El Milagro',
		'El Parco',
		'Florida',
		'Granada',
		'Huambo',
		'Huancas',
		'Imaza',
		'Inguilpata',
		'Jamalca',
		'Jazán',
		'Jumbilla',
		'La Jalca',
		'La Peca',
		'Lámud',
		'Levanto',
		'Leymebamba',
		'Limabamba',
		'Longar',
		'Longuita',
		'Lonya Chico',
		'Lonya Grande',
		'Luya Viejo',
		'Luya',
		'Magdalena',
		'María',
		'Mariscal Benavides',
		'Mariscal Castilla',
		'Milpuc',
		'Molinopampa',
		'Montevideo',
		'Nieva',
		'Ocalli',
		'Ocumal',
		'Olleros',
		'Omia',
		'Pisuquía',
		'Providencia',
		'Quinjalca',
		'Recta',
		'Río Santiago',
		'San Carlos',
		'San Cristóbal',
		'San Francisco de Daguas',
		'San Francisco del Yeso',
		'San Isidro de Maino',
		'San Jerónimo',
		'San Juan de Lopecancha',
		'San Nicolás',
		'Santa Catalina',
		'Santa Rosa',
		'Santo Tomás',
		'Shipasbamba',
		'Soloco',
		'Sonche',
		'Tingo',
		'Totora',
		'Trita',
		'Valera',
		'Vista Alegre',
		'Yambrasbamba',
		'Yamón'
	),
	'ANC' => array(
		'Abelardo Pardo Lezameta',
		'Acas',
		'Aco',
		'Acobamba',
		'Acochaca',
		'Acopampa',
		'Aczo',
		'Aija',
		'Alfonso Ugarte',
		'Amashca',
		'Anra',
		'Anta',
		'Antonio Raymondi',
		'Aquia',
		'Ataquero',
		'Bambas',
		'Bolognesi',
		'Buena Vista Alta',
		'Cabana',
		'Cáceres del Perú',
		'Cajacay',
		'Cajamarquilla',
		'Cajay',
		'Canis',
		'Caraz',
		'Carhuapampa',
		'Carhuaz',
		'Casca',
		'Cascapara',
		'Cashapampa',
		'Casma',
		'Cátac',
		'Chacas',
		'Chaccho',
		'Chavín de Huántar',
		'Chimbote',
		'Chingalpo',
		'Chingas',
		'Chiquián',
		'Cochabamba',
		'Cochapeti',
		'Cochas',
		'Coishco',
		'Colcabamba',
		'Colquioc',
		'Comandante Noel',
		'Conchucos',
		'Congas',
		'Coris',
		'Corongo',
		'Cotaparaco',
		'Culebras',
		'Cusca',
		'Eleazar Guzmán Barrón',
		'Fidel OIivas Escudero',
		'Huacachi',
		'Huacaschuque',
		'Huacchis',
		'Huachis',
		'Huacllán',
		'Huallanca',
		'Huallanca',
		'Huanchay',
		'Huandoval',
		'Huántar',
		'Huaraz',
		'Huari',
		'Huarmey',
		'Huasta',
		'Huata',
		'Huayan',
		'Huaylas',
		'Huayllabamba',
		'Huayllacayán',
		'Huayllán',
		'Huayllapampa',
		'Independencia',
		'Jangas',
		'La Libertad',
		'La Merced',
		'La Pampa',
		'La Primavera',
		'Lacabamba',
		'Llacllín',
		'Llama',
		'Llamellín',
		'Llapo',
		'Llipa',
		'Llumpa',
		'Lucma',
		'Macate',
		'Malvas',
		'Mancos',
		'Mangas',
		'Marca',
		'Marcará',
		'Masin',
		'Matacoto',
		'Mato',
		'Mirgas',
		'Moro',
		'Musga',
		'Nepeña',
		'Nuevo Chimbote (← Chimbote)',
		'Ocros',
		'Olleros',
		'Pacllón',
		'Pallasca',
		'Pamparomás',
		'Pampas Chico',
		'Pampas',
		'Pampas',
		'Pararín',
		'Pariacoto',
		'Pariahuanca',
		'Parobamba',
		'Paucas',
		'Pira',
		'Piscobamba',
		'Pomabamba',
		'Pontó',
		'Pueblo Libre',
		'Quiches',
		'Quillo',
		'Quinuabamba',
		'Ragash',
		'Rahuapampa',
		'Ranrahírca',
		'Rapayán',
		'Recuay',
		'Samanco',
		'San Cristóbal de Raján',
		'San Juan de Rontoy',
		'San Juan',
		'San Luis',
		'San Marcos',
		'San Miguel de Aco',
		'San Miguel de Corpanqui',
		'San Nicolás',
		'San Pedro de Chaná',
		'San Pedro',
		'Santa Cruz',
		'Santa Rosa',
		'Santa',
		'Santiago de Chilcas',
		'Santo Toribio',
		'Shilla',
		'Shupluy',
		'Sicsibamba',
		'Sihuas',
		'Succha',
		'Tapacocha',
		'Tarica',
		'Tauca',
		'Ticapampa',
		'Ticllos',
		'Tinco',
		'Uco',
		'Yánac',
		'Yanama',
		'Yaután',
		'Yauya',
		'Yungar',
		'Yungay',
		'Yupán',
		'Yuracmarca'
	),
	'APU' => array(
		'Abancay',
		'Anccohuayllo',
		'Andahuaylas',
		'Andarapa',
		'Antabamba',
		'Capaya',
		'Caraybamba',
		'Chacoche',
		'Chalhuahuacho',
		'Chalhuanca',
		'Chapimarca',
		'Chiara',
		'Chincheros',
		'Chuquibambilla',
		'Circa',
		'Cocharcas',
		'Colcabamba',
		'Cotabambas',
		'Cotaruse',
		'Coyllurqui',
		'Curahuasi',
		'Curasco',
		'Curpahuasi',
		'El Oro',
		'El Porvenir',
		'Haquira',
		'Huaccana',
		'Huancarama',
		'Huancaray',
		'Huanipaca',
		'Huaquirca',
		'Huayana',
		'Huayllati',
		'Huayllu',
		'José María Arguedas',
		'Juan Espinoza Medrano',
		'Justo Apu Sahuaraura',
		'Kaquiabamba',
		'Kishuara',
		'Lambrama',
		'Los Chankas',
		'Lucre',
		'Mamara',
		'Mara',
		'Mariscal Gamarra',
		'Micaela Bastidas',
		'Ocobamba',
		'Ongoy',
		'Oropesa',
		'Pachaconas',
		'Pacobamba',
		'Pacucha',
		'Pampachiri',
		'Pataypampa',
		'Pichirhua',
		'Pocohuanca',
		'Pomacocha',
		'Progreso',
		'Ranracancha',
		'Rocchacc',
		'Sabaino',
		'San Antonio de Cachi',
		'San Antonio',
		'San Jerónimo',
		'San Juan de Chacña',
		'San Miguel de Chaccrapampa',
		'San Pedro de Cachora',
		'Santa María de Chicmo',
		'Santa Rosa',
		'Sañayca',
		'Soraya',
		'Talavera',
		'Tambobamba',
		'Tamburco',
		'Tapairihua',
		'Tintay',
		'Toraya',
		'Tumay Huaraca',
		'Turpay',
		'Turpo',
		'Uranmarca',
		'Vilcabamba',
		'Virundo',
		'Yanaca',
	),
	'ARE' => array(
		'Acarí',
		'Achoma',
		'Alca',
		'Alto Selva Alegre',
		'Andagua',
		'Andaray',
		'Aplao',
		'Arequipa',
		'Atico',
		'Atiquipa',
		'Ayo',
		'Bella Unión',
		'Cabanaconde',
		'Cahuacho',
		'Callalli',
		'Camaná',
		'Caravelí',
		'Cayarani',
		'Caylloma',
		'Cayma',
		'Cerro Colorado',
		'Chachas',
		'Chala',
		'Chaparra',
		'Characato',
		'Charcana',
		'Chichas',
		'Chiguata',
		'Chilcaymarca',
		'Chivay',
		'Choco',
		'Chuquibamba',
		'Cocachacra',
		'Coporaque',
		'Cotahuasi',
		'Deán Valdivia',
		'Huambo',
		'Huanca',
		'Huancarqui',
		'Huanuhuanu',
		'Huaynacotas',
		'Ichupampa',
		'Iray',
		'Islay',
		'Jacobo Hunter',
		'Jaqui',
		'José Luis Bustamante y Rivero',
		'José María Quimper',
		'La Joya',
		'Lari',
		'Lluta',
		'Lomas',
		'Maca',
		'Machaguay',
		'Madrigal',
		'Majes',
		'Mariano Melgar',
		'Mariano Nicolás Valcárcel',
		'Mariscal Cáceres',
		'Mejía',
		'Miraflores',
		'Mollebaya',
		'Mollendo',
		'Nicolás de Piérola',
		'Ocoña',
		'Orcopampa',
		'Pampacolca',
		'Pampamarca',
		'Paucarpata',
		'Pocsi',
		'Polobaya',
		'Punta de Bombón',
		'Puyca',
		'Quechualla',
		'Quequeña',
		'Quicacha',
		'Quilca',
		'Río Grande',
		'Sabandía',
		'Sachaca',
		'Salamanca',
		'Samuel Pastor',
		'San Antonio de Chuca',
		'San Juan de Siguas',
		'San Juan de Tarucani',
		'Santa Isabel de Siguas',
		'Santa Rita de Siguas',
		'Sayla',
		'Sibayo',
		'Socabaya',
		'Tapay',
		'Tauría',
		'Tiabaya',
		'Tipán',
		'Tisco',
		'Tomepampa',
		'Toro',
		'Tuti',
		'Uchumayo',
		'Uñón',
		'Uraca',
		'Viraco',
		'Vítor',
		'Yanahuara',
		'Yanaquihua',
		'Yanque',
		'Yarabamba',
		'Yauca',
		'Yura'
	),
	'AYA' => array(
		'Accomarca',
		'Acocro',
		'Acos Vinchos',
		'Alcamenca',
		'Anchihuay',
		'Anco',
		'Andrés Avelino Cáceres Dorregaray',
		'Apongo',
		'Asquipata',
		'Aucara',
		'Ayacucho',
		'Ayahuanco',
		'Ayna',
		'Belén',
		'Cabana',
		'Canaria',
		'Canayre',
		'Cangallo',
		'Carapo',
		'Carhuanca',
		'Carmen Alto',
		'Carmen Salcedo',
		'Cayara',
		'Chaca',
		'Chalcos',
		'Chaviña',
		'Chiara',
		'Chilcas',
		'Chilcayoc',
		'Chipao',
		'Chumpi',
		'Chungui',
		'Chuschi',
		'Colca',
		'Colta',
		'Concepción',
		'Coracora',
		'Corculla',
		'Coronel Castañeda',
		'Huacaña',
		'Huac-Huas',
		'Huamanguilla',
		'Huamanquiquia',
		'Huambalpa',
		'Huancapi',
		'Huancaraylla',
		'Huanta',
		'Huaya',
		'Iguaín',
		'Independencia',
		'Jesús Nazareno',
		'Lampa',
		'Laramate',
		'Leoncio Prado',
		'Llauta',
		'Llochegua',
		'Los Morochucos',
		'Lucanas',
		'Luis Carranza',
		'Luricocha',
		'Marcabamba',
		'María Parado de Bellido',
		'Morcolla',
		'Ocaña',
		'Ocros',
		'Oronccoy',
		'Otoca',
		'Oyolo',
		'Pacapausa',
		'Pacaycasa',
		'Paico',
		'Pararca',
		'Paras',
		'Pausa',
		'Pucacolpa',
		'Pullo',
		'Puquio',
		'Puyusca',
		'Querobamba',
		'Quinua',
		'Sacsamarca',
		'Saisa',
		'Samugari',
		'San Cristóbal',
		'San Francisco de Ravacayco',
		'San Javier de Alpabamba',
		'San José de Ticllas',
		'San José de Ushua',
		'San Juan Bautista',
		'San Juan',
		'San Miguel',
		'San Pedro de Larcay',
		'San Pedro de Palco',
		'San Pedro',
		'San Salvador de Quije',
		'Sancos',
		'Sancos',
		'Santa Ana de Huaycahuacho',
		'Santa Lucía',
		'Santa Rosa',
		'Santiago de Lucanamarca',
		'Santiago de Paucaray',
		'Santiago de Pischa',
		'Santillana',
		'Sara Sara',
		'Sarhua',
		'Saurama',
		'Sivia',
		'Socos',
		'Soras',
		'Tambillo',
		'Tambo',
		'Totos',
		'Uchuraccay',
		'Upahuacho',
		'Vilcanchos',
		'Vilcashuamán',
		'Vinchos',
		'Vischongo'
	),
	'CAJ' => array(
		'Andabamba',
		'Anguía',
		'Asunción',
		'Bambamarca',
		'Baños del Inca',
		'Bellavista',
		'Bolívar',
		'Cachachi',
		'Cajabamba',
		'Cajamarca',
		'Callayuc',
		'Calquis',
		'Catache',
		'Catilluc',
		'Celendín',
		'Chadín',
		'Chalamarca',
		'Chancay',
		'Chancaybaños',
		'Chetilla',
		'Chiguirip',
		'Chilete',
		'Chimban',
		'Chirinos',
		'Chontalí',
		'Choropampa',
		'Choros',
		'Chota',
		'Chugur',
		'Chumuch',
		'Cochabamba',
		'Colasay',
		'Conchán',
		'Condebamba',
		'Contumazá',
		'Cortegana',
		'Cospán',
		'Cujillo',
		'Cupisnique',
		'Cutervo',
		'Eduardo Villanueva',
		'El Prado',
		'Encañada',
		'Gregorio Pita',
		'Guzmango',
		'Huabal',
		'Hualgayoc',
		'Huambos',
		'Huarango',
		'Huasmin',
		'Ichocán',
		'Jaén',
		'Jesús',
		'Jorge Chávez',
		'José Gálvez',
		'José Manuel Quiroz',
		'José Sabogal',
		'La Coipa',
		'La Esperanza',
		'La Florida',
		'La Libertad de Pallán',
		'La Ramada',
		'Lajas',
		'Las Pirias',
		'Llacanora',
		'Llama',
		'Llapa',
		'Magdalena',
		'Matara',
		'Miguel Iglesias',
		'Miracosta',
		'Namballe',
		'Namora',
		'Nanchoc',
		'Niepos',
		'Ninabamba',
		'Oxamarca',
		'Paccha',
		'Pedro Gálvez',
		'Pimpingos',
		'Pión',
		'Pomahuaca',
		'Pucará',
		'Pulán',
		'Querocotillo',
		'Querocoto',
		'Sallique',
		'San Andrés de Cutervo',
		'San Benito',
		'San Bernardino',
		'San Felipe',
		'San Gregorio',
		'San Ignacio',
		'San José de Lourdes',
		'San José del Alto',
		'San Juan de Cutervo',
		'San Juan de Licupis',
		'San Juan',
		'San Luis de Lucma',
		'San Luis',
		'San Miguel',
		'San Pablo',
		'San Silvestre de Cochán',
		'Santa Cruz de Toledo',
		'Santa Cruz',
		'Santa Cruz',
		'Santa Rosa',
		'Santo Domingo de la Capilla',
		'Santo Tomás',
		'Saucepampa',
		'Sexi',
		'Sitacocha',
		'Socota',
		'Sorochuco',
		'Sucre',
		'Tabaconas',
		'Tacabamba',
		'Tantarica',
		'Tocmoche',
		'Tongod',
		'Toribio Casanova',
		'Tumbaden',
		'Unión Agua Blanca',
		'Utco',
		'Uticyacu',
		'Yauyucan',
		'Yonán'
	),
	'CUS' => array(
		'Accha',
		'Acomayo',
		'Acopía',
		'Acos',
		'Alto Pichigua',
		'Ancahuasi',
		'Andahuaylillas',
		'Anta',
		'Cachimayo',
		'Caicay',
		'Calca',
		'Camanti',
		'Capacmarca',
		'Ccapi',
		'Ccarhuayo',
		'Ccatca',
		'Ccorca',
		'Challabamba',
		'Chamaca',
		'Checacupe',
		'Checca',
		'Chinchaypujio',
		'Chinchero',
		'Colcha',
		'Colquemarca',
		'Colquepata',
		'Combapata',
		'Condoroma',
		'Coporaque',
		'Coya',
		'Cusco',
		'Cusipata',
		'Echarati',
		'Espinar',
		'Huancarani',
		'Huanoquite',
		'Huaro',
		'Huarocondo',
		'Huayllabamba',
		'Huayopata',
		'Inkawasi',
		'Kimbiri',
		'Kosñipata',
		'Kunturkanki',
		'Lamay',
		'Langui',
		'Lares',
		'Layo',
		'Limatambo',
		'Livitaca',
		'Llusco',
		'Lucre',
		'Machupicchu',
		'Marangani',
		'Maranura',
		'Maras',
		'Marcapata',
		'Megantoni',
		'Mollepata',
		'Mosoc Llacta',
		'Ocobamba',
		'Ocongate',
		'Ocoruro',
		'Ollantaytambo',
		'Omacha',
		'Oropesa',
		'Paccaritambo',
		'Pallpata',
		'Pampamarca',
		'Paruro',
		'Paucartambo',
		'Pichari',
		'Pichigua',
		'Pillpinto',
		'Písac',
		'Pitumarca',
		'Pomacanchi',
		'Poroy',
		'Pucyura',
		'Quehue',
		'Quelloúno',
		'Quiñota',
		'Quiquijana',
		'Rondocan',
		'San Jerónimo',
		'San Pablo',
		'San Pedro',
		'San Salvador',
		'San Sebastián',
		'Sangarará',
		'Santa Ana',
		'Santa Teresa',
		'Santiago',
		'Santo Tomás',
		'Saylla',
		'Sicuani',
		'Suyckutambo',
		'Taray',
		'Tinta',
		'Túpac Amaru',
		'Urcos',
		'Urubamba',
		'Velille',
		'Vilcabamba',
		'Villa Kintiarina',
		'Villa Virgen',
		'Wánchaq',
		'Yanaoca',
		'Yanatile',
		'Yaurisque',
		'Yucay',
		'Zurite'
	),
	'HUV' => array(
		'Acobamba',
		'Acobambilla',
		'Acoria',
		'Acostambo',
		'Acraquia',
		'Ahuaycha',
		'Anchonga',
		'Anco',
		'Andabamba',
		'Andaymarca',
		'Anta',
		'Arma',
		'Ascensión',
		'Aurahuá',
		'Ayaví',
		'Caja',
		'Callanmarca',
		'Capillas',
		'Castrovirreyna',
		'Ccochaccasa',
		'Chinchihuasi',
		'Chincho',
		'Chupamarca',
		'Churcampa',
		'Cocas',
		'Colcabamba',
		'Conayca',
		'Congalla',
		'Córdova',
		'Cosme (← Anco)',
		'Cuenca',
		'Daniel Hernández',
		'El Carmen',
		'Huachocolpa',
		'Huachocolpa',
		'Huachos',
		'Huamatambo',
		'Huanca Huanca',
		'Huancavelica',
		'Huando',
		'Huaribamba',
		'Huayacundo Arma',
		'Huayllahuara',
		'Huayllay Grande',
		'Huaytará',
		'Izcuchaca',
		'Julcamarca',
		'La Merced',
		'Laramarca',
		'Laria',
		'Lircay',
		'Locroja',
		'Manta',
		'Marcas',
		'Mariscal Cáceres',
		'Mollepampa',
		'Moya',
		'Nuevo Occoro',
		'Ñahuimpuquio',
		'Ocoyo',
		'Pachamarca',
		'Palca',
		'Pampas',
		'Paucará',
		'Paucarbamba',
		'Pazos',
		'Pichos',
		'Pilchaca',
		'Pilpichaca',
		'Pomacocha',
		'Querco',
		'Quichuas',
		'Quishuar',
		'Quito-Arma',
		'Roble',
		'Rosario',
		'Salcabamba',
		'Salcahuasi',
		'San Antonio de Antaparco',
		'San Antonio de Cusicancha',
		'San Francisco de Sangayaico',
		'San Isidro',
		'San Juan',
		'San Marcos de Rocchac',
		'San Miguel de Mayocc',
		'San Pedro de Coris',
		'Santa Ana',
		'Santiago de Chocorvos',
		'Santiago de Quirahuara',
		'Santiago de Tucuma',
		'Santo Domingo de Capillas',
		'Santo Tomás de Pata',
		'Seclla',
		'Surcubamba',
		'Tambo',
		'Tantara',
		'Ticrapo',
		'Tintay Puncu',
		'Vilca',
		'Yauli'
	),
	'HUC' => array(
		'Amarilis',
		'Ambo',
		'Aparicio Pomares',
		'Arancay',
		'Baños',
		'Cahuac',
		'Canchabamba',
		'Castillo Grande',
		'Cayna',
		'Chacabamba',
		'Chaglla',
		'Chavín de Pariarca',
		'Chavinillo',
		'Chinchao',
		'Cholón',
		'Choras',
		'Chuquis',
		'Churubamba',
		'Cochabamba',
		'Codo del Pozuzo',
		'Colpas',
		'Conchamarca',
		'Daniel Alomía Robles',
		'Hermilio Valdizán',
		'Honoria',
		'Huácar',
		'Huacaybamba',
		'Huacrachuco',
		'Huánuco',
		'Jacas Chico',
		'Jacas Grande',
		'Jesús',
		'Jircan',
		'Jivia',
		'José Crespo y Castillo',
		'La Morada',
		'La Unión',
		'Llata',
		'Luyando',
		'Margos',
		'Mariano Dámaso Beraún',
		'Marías',
		'Miraflores',
		'Molino',
		'Monzón',
		'Obas',
		'Pachas',
		'Pampamarca',
		'Panao',
		'Pillco Marca',
		'Pinra',
		'Pucayacu',
		'Pueblo Nuevo',
		'Puerto Inca',
		'Punchao',
		'Puños',
		'Queropalca',
		'Quisqui',
		'Quivilla',
		'Ripán',
		'Rondos',
		'Rupa-Rupa',
		'San Buenaventura',
		'San Francisco de Asís',
		'San Francisco de Cayrán',
		'San Francisco',
		'San Miguel de Cauri',
		'San Pablo de Pillao',
		'San Pedro de Chaulán',
		'San Rafael',
		'Santa María del Valle',
		'Santa Rosa de Alto Yanajanca',
		'Santo Domingo de Anda',
		'Shunqui',
		'Sillapata',
		'Singa',
		'Tantamayo',
		'Tomay Kichwa',
		'Tournavista',
		'Umari',
		'Yacus (← Amarilis)',
		'Yanas',
		'Yarumayo',
		'Yuyapichis'
	),
	'ICA' => array(
		'Alto Larán',
		'Changuillo',
		'Chavín',
		'Chincha Alta',
		'Chincha Baja',
		'El Carmen',
		'El Ingenio',
		'Grocio Prado',
		'Huancano',
		'Humay',
		'Ica',
		'Independencia',
		'La Tinguiña',
		'Llipata',
		'Los Aquijes',
		'Marcona',
		'Nazca',
		'Ocucaje',
		'Pachacutec',
		'Palpa',
		'Paracas',
		'Parcona',
		'Pisco',
		'Pueblo Nuevo',
		'Río Grande',
		'Salas',
		'San Andrés',
		'San Clemente',
		'San José de los Molinos',
		'San Juan Bautista',
		'San Juan de Yanac',
		'San Pedro de Huacarpana',
		'Santa Cruz',
		'Santiago',
		'Subtanjalla',
		'Sunampe',
		'Tambo de Mora',
		'Tate',
		'Tibillo',
		'Túpac Amaru Inca',
		'Vista Alegre',
		'Yauca del Rosario'
	),
	'JUN' => array(
		'Aco',
		'Acobamba',
		'Acolla',
		'Áhuac',
		'Andamarca',
		'Apata',
		'Ataura',
		'Canchayllo',
		'Carhuacallanga',
		'Carhuamayo',
		'Chacapalpa',
		'Chacapampa',
		'Chambara',
		'Chanchamayo',
		'Chicche',
		'Chilca',
		'Chongos Alto',
		'Chongos Bajo',
		'Chupaca',
		'Chupuro',
		'Cochas',
		'Colca',
		'Comas',
		'Concepción',
		'Coviriali',
		'Cullhuas',
		'Curicaca',
		'El Mantaro',
		'El Tambo',
		'Heroínas Toledo',
		'Huáchac',
		'Huacrapuquio',
		'Hualhuas',
		'Huamalí',
		'Huamancaca Chico',
		'Huancán',
		'Huancayo',
		'Huaricolca',
		'Huaripampa',
		'Huasahuasi',
		'Huasicancha',
		'Huay-Huay',
		'Huayucachi',
		'Huertas',
		'Ingenio',
		'Janjaillo',
		'Jauja',
		'Julcán',
		'Junín',
		'La Oroya',
		'La Unión',
		'Leonor Ordóñez',
		'Llaylla',
		'Llocllapampa',
		'Manzanares',
		'Marcapomacocha',
		'Marco',
		'Mariscal Castilla',
		'Masma Chicche',
		'Masma',
		'Matahuasi',
		'Mazamari',
		'Mito',
		'Molinos',
		'Monobamba',
		'Morococha',
		'Muqui',
		'Muquiyauyo',
		'Nueve de Julio',
		'Ondores',
		'Orcotuna',
		'Paca',
		'Paccha',
		'Palca',
		'Palcamayo',
		'Pampa Hermosa',
		'Pancán',
		'Pangoa',
		'Parco',
		'Pariahuanca',
		'Perené',
		'Pichanaqui',
		'Pilcomayo',
		'Pomacancha',
		'Pucará',
		'Quichuay',
		'Quilcas',
		'Ricrán',
		'Río Negro',
		'Río Tambo',
		'San Agustín de Cajas',
		'San Jerónimo de Tunán',
		'San José de Quero',
		'San Juan de Jarpa',
		'San Juan de Yscos',
		'San Lorenzo',
		'San Luis de Shuaro',
		'San Pedro de Cajas',
		'San Pedro de Chunán',
		'San Pedro de Saño',
		'San Ramón',
		'Santa Bárbara de Carhuacayán',
		'Santa Rosa de Ocopa',
		'Santa Rosa de Sacco',
		'Santo Domingo de Acobamba',
		'Sapallanga',
		'Satipo',
		'Sausa',
		'Sicaya',
		'Sincos',
		'Suitucancha',
		'Tapo',
		'Tarma',
		'Tres de Diciembre',
		'Tunán Marca',
		'Ulcumayo',
		'Viques',
		'Vítoc',
		'Vizcatán del Ene',
		'Yanacancha',
		'Yauli',
		'Yauyos'
	),
	'LAL' => array(
		'Agallpampa',
		'Angasmarca',
		'Ascope',
		'Bambamarca',
		'Bolívar',
		'Buldibuyo',
		'Cachicadán',
		'Calamarca',
		'Carabamba',
		'Casa Grande',
		'Cascas',
		'Chao',
		'Charat',
		'Chepén',
		'Chicama',
		'Chillia',
		'Chocope',
		'Chugay',
		'Cochorco',
		'Condormarca',
		'Curgos',
		'El Porvenir',
		'Florencia de Mora',
		'Guadalupe',
		'Guadalupito',
		'Huamachuco',
		'Huancaspata',
		'Huanchaco',
		'Huaranchal',
		'Huaso',
		'Huaylillas',
		'Huayo',
		'Jequetepeque',
		'Julcán',
		'La Cuesta',
		'La Esperanza',
		'Laredo',
		'Longotea',
		'Lucma',
		'Mache',
		'Magdalena de Cao',
		'Marcabal',
		'Marmot',
		'Moche',
		'Mollebamba',
		'Mollepata',
		'Ongón',
		'Otuzco',
		'Pacanga',
		'Pacasmayo',
		'Paiján',
		'Paranday',
		'Parcoy',
		'Pataz',
		'Pias',
		'Poroto',
		'Pueblo Nuevo',
		'Quiruvilca',
		'Rázuri',
		'Salaverry',
		'Salpo',
		'San José',
		'San Pedro de Lloc',
		'Sanagorán',
		'Santa Cruz de Chuca',
		'Santiago de Cao',
		'Santiago de Challas',
		'Santiago de Chuco',
		'Sarín',
		'Sartimbamba',
		'Sayapullo',
		'Simbal',
		'Sinsicap',
		'Sitabamba',
		'Taurija',
		'Tayabamba',
		'Trujillo',
		'Uchumarca',
		'Ucuncha',
		'Urpay',
		'Usquil',
		'Víctor Larco Herrera',
		'Virú'
	),
	'LAM' => array(
		'Cañaris',
		'Cayaltí',
		'Chiclayo',
		'Chóchope',
		'Chongoyape',
		'Eten',
		'Ferreñafe',
		'Íllimo',
		'Incahuasi',
		'Jayanca',
		'José Leonardo Ortiz',
		'La Victoria',
		'Lagunas',
		'Lambayeque',
		'Manuel Antonio Mesones Muro',
		'Mochumí',
		'Monsefú',
		'Mórrope',
		'Motupe',
		'Nueva Arica',
		'Olmos',
		'Oyotún',
		'Pacora',
		'Pátapo',
		'Picsi',
		'Pimentel',
		'Pítipo',
		'Pomalca',
		'Pucalá',
		'Pueblo Nuevo',
		'Puerto Eten',
		'Reque',
		'Salas',
		'San José',
		'Santa Rosa',
		'Saña',
		'Túcume',
		'Tumán'
	),
	'LIM' => array(
		'Alis',
		'Ámbar',
		'Andajes',
		'Antioquía',
		'Arahuay',
		'Asia',
		'Atavillos Alto',
		'Atavillos Bajo',
		'Aucallama',
		'Ayauca',
		'Ayaviri',
		'Azángaro',
		'Barranca',
		'Cacra',
		'Cajatambo',
		'Calango',
		'Caleta de Carquín',
		'Callahuanca',
		'Canta',
		'Carampoma',
		'Carania',
		'Catahuasi',
		'Caujul',
		'Cerro Azul',
		'Chancay',
		'Checras',
		'Chicla',
		'Chilca',
		'Chocos',
		'Coayllo',
		'Cochamarca',
		'Cochas',
		'Colonia',
		'Copa',
		'Cuenca',
		'Gorgor',
		'Hongos',
		'Huacho',
		'Huachupampa',
		'Hualmay',
		'Huamantanga',
		'Huampara',
		'Huancapón',
		'Huancaya',
		'Huangáscar',
		'Huantán',
		'Huanza',
		'Huañec',
		'Huaral',
		'Huarochirí',
		'Huaros',
		'Huaura',
		'Ihuarí',
		'Imperial',
		'Lachaqui',
		'Lahuaytambo',
		'Lampián',
		'Langa',
		'Laraos',
		'Laraos',
		'Leoncio Prado',
		'Lincha',
		'Lunahuaná',
		'Madeán',
		'Mala',
		'Manás',
		'Mariatana',
		'Matucana',
		'Miraflores',
		'Naván',
		'Nuevo Imperial',
		'Omas',
		'Oyón',
		'Pacarán',
		'Pacaraos',
		'Paccho',
		'Pachangara',
		'Paramonga',
		'Pativilca',
		'Putinza',
		'Quilmaná',
		'Quinches',
		'Quinocay',
		'Ricardo Palma',
		'San Andrés de Tupicocha',
		'San Antonio',
		'San Antonio',
		'San Bartolomé',
		'San Buenaventura',
		'San Damián',
		'San Joaquín',
		'San Juan de Iris',
		'San Juan de Tantaranche',
		'San Lorenzo de Quinti',
		'San Luis',
		'San Mateo de Otao',
		'San Mateo',
		'San Miguel de Acos',
		'San Pedro de Casta',
		'San Pedro de Huancayre',
		'San Pedro de Pilas',
		'San Vicente de Cañete',
		'Sangallaya',
		'Santa Cruz de Andamarca',
		'Santa Cruz de Cocachacra',
		'Santa Cruz de Flores',
		'Santa Eulalia',
		'Santa Leonor',
		'Santa María',
		'Santa Rosa de Quives',
		'Santiago de Anchucaya',
		'Santiago de Tuna',
		'Santo Domingo de los Olleros',
		'Sayán',
		'Sumbilca',
		'Supe Puerto',
		'Supe',
		'Surco',
		'Tanta',
		'Tauripampa',
		'Tomas',
		'Tupe',
		'Végueta',
		'Veintisiete de Noviembre',
		'Viñac',
		'Vitis',
		'Yauyos',
		'Zúñiga'
	),
	'LMA' => array(
		'Ancón',
		'Ate',
		'Barranco',
		'Breña',
		'Carabayllo',
		'Chaclacayo',
		'Chorrillos',
		'Cieneguilla',
		'Comas',
		'El Agustino',
		'Independencia',
		'Jesús María',
		'La Molina',
		'La Victoria',
		'Lima (Cercado de Lima)',
		'Lince',
		'Los Olivos',
		'Lurigancho (Chosica)',
		'Lurín',
		'Magdalena del Mar',
		'Miraflores',
		'Pachacámac',
		'Pucusana',
		'Pueblo Libre (Magdalena Vieja)',
		'Puente Piedra',
		'Punta Hermosa',
		'Punta Negra',
		'Rímac',
		'San Bartolo',
		'San Borja',
		'San Isidro',
		'San Juan de Lurigancho',
		'San Juan de Miraflores',
		'San Luis',
		'San Martín de Porres (Barrio Obrero Industrial 27 de Octubre)',
		'San Miguel',
		'Santa Anita',
		'Santa María del Mar',
		'Santa Rosa',
		'Santiago de Surco',
		'Surquillo',
		'Villa El Salvador',
		'Villa María del Triunfo'
	),
	'LOR' => array(
		'Alto Nanay',
		'Alto Tapiche',
		'Andoas',
		'Balsapuerto',
		'Barranca',
		'Belén',
		'Cahuapanas',
		'Capelo',
		'Contamana',
		'Emilio San Martín',
		'Fernando Lores',
		'Inahuaya',
		'Indiana',
		'Iquitos',
		'Jeberos',
		'Jenaro Herrera',
		'Lagunas',
		'Las Amazonas',
		'Manseriche',
		'Maquía',
		'Mazán',
		'Morona',
		'Napo',
		'Nauta',
		'Padre Márquez',
		'Pampa Hermosa',
		'Parinari',
		'Pastaza',
		'Pebas',
		'Puinahua',
		'Punchana',
		'Putumayo',
		'Ramón Castilla',
		'Requena',
		'Rosa Panduro',
		'San Juan Bautista',
		'San Pablo',
		'Santa Cruz',
		'Saquena',
		'Sarayacu',
		'Soplin',
		'Tapiche',
		'Teniente César López Rojas',
		'Teniente Manuel Clavero',
		'Tigre',
		'Torres Causana',
		'Trompeteros',
		'Urarinas',
		'Vargas Guerra',
		'Yaguas',
		'Yaquerana',
		'Yavarí',
		'Yurimaguas'
	),
	'MDD' => array(
		'Fitzcarrald',
		'Huepetuhe',
		'Iberia',
		'Inambari',
		'Iñapari',
		'Laberinto',
		'Las Piedras',
		'Madre de Dios',
		'Manu',
		'Tahuamanu',
		'Tambopata'
	),
	'MOQ' => array(
		'Carumas',
		'Chojata',
		'Coalaque',
		'Cuchumbaya',
		'El Algarrobal',
		'Ichuña',
		'Ilo',
		'La Capilla',
		'Lloque',
		'Matalaque',
		'Moquegua',
		'Omate',
		'Pacocha',
		'Puquina',
		'Quinistaquillas',
		'Samegua',
		'San Cristóbal',
		'Torata',
		'Ubinas',
		'Yunga'
	),
	'PAS' => array(
		'Chacayán',
		'Chaupimarca',
		'Chontabamba',
		'Constitución',
		'Goyllarisquizga',
		'Huachón',
		'Huancabamba',
		'Huariaca',
		'Huayllay',
		'Ninacaca',
		'Oxapampa',
		'Palcazú',
		'Pallanchacra',
		'Paucar',
		'Paucartambo',
		'Pozuzo',
		'Puerto Bermúdez',
		'San Francisco de Asís de Yarusyacán',
		'San Pedro de Pillao',
		'Santa Ana de Tusi',
		'Simón Bolívar',
		'Tápuc',
		'Ticlacayán',
		'Tinyahuarco',
		'Vicco',
		'Vilcabamba',
		'Villa Rica',
		'Yanacancha',
		'Yanahuanca'
	),
	'PIU' => array(
		'Amotape',
		'Arenal',
		'Ayabaca',
		'Bellavista de la Unión',
		'Bellavista',
		'Bernal',
		'Buenos Aires',
		'Canchaque',
		'Castilla',
		'Catacaos',
		'Chalaco',
		'Chulucanas',
		'Colán',
		'Cristo nos Valga',
		'Cura Mori',
		'El Alto',
		'El Carmen de la Frontera',
		'El Tallán',
		'Frías',
		'Huancabamba',
		'Huarmaca',
		'Ignacio Escudero',
		'Jililí',
		'La Arena',
		'La Brea',
		'La Huaca',
		'La Matanza',
		'La Unión',
		'Lagunas',
		'Lalaquiz',
		'Lancones',
		'Las Lomas',
		'Lobitos',
		'Los Órganos',
		'Máncora',
		'Marcavelica',
		'Miguel Checa',
		'Montero',
		'Morropón',
		'Pacaipampa',
		'Paimas',
		'Paita',
		'Pariñas',
		'Piura',
		'Querecotillo',
		'Rinconada-Llicuar',
		'Salitral',
		'Salitral',
		'San Juan de Bigote',
		'San Miguel de El Faique',
		'Santa Catalina de Mossa',
		'Santo Domingo',
		'Sapillica',
		'Sechura',
		'Sícchez',
		'Sóndor',
		'Sondorillo',
		'Sullana',
		'Suyo',
		'Tamarindo',
		'Tambo Grande',
		'Veintiséis de Octubre',
		'Vice',
		'Vichayal',
		'Yamango'
	),
	'PUN' => array(
		'Achaya',
		'Ácora',
		'Ajoyani',
		'Alto Inambari',
		'Amantaní',
		'Ananea',
		'Anapia',
		'Antauta',
		'Arapa',
		'Asillo',
		'Atuncolla',
		'Ayapata',
		'Ayaviri',
		'Azángaro',
		'Cabana',
		'Cabanilla',
		'Cabanillas',
		'Calapuja',
		'Caminaca',
		'Capachica',
		'Capazo',
		'Caracoto',
		'Chucuito',
		'Chupa',
		'Coasa',
		'Coata',
		'Cojata',
		'Conduriri',
		'Conima',
		'Copani',
		'Corani',
		'Crucero',
		'Cupi',
		'Cuturapi',
		'Cuyocuyo',
		'Desaguadero',
		'Huacullani',
		'Huancané',
		'Huata',
		'Huatasani',
		'Huayrapata',
		'Ilave',
		'Inchupalla',
		'Ituata',
		'José Domingo Choquehuanca',
		'Juli',
		'Juliaca',
		'Kelluyo',
		'Lampa',
		'Limbani',
		'Llalli',
		'Macari',
		'Macusani',
		'Mañazo',
		'Moho',
		'Muñani',
		'Nicasio',
		'Nuñoa',
		'Ocuviri',
		'Ollachea',
		'Ollaraya',
		'Orurillo',
		'Palca',
		'Paratía',
		'Patambuco',
		'Paucarcolla',
		'Pedro Vilca Apaza',
		'Phara',
		'Pichacani',
		'Pilcuyo',
		'Pisacoma',
		'Platería',
		'Pomata',
		'Potoni',
		'Pucará',
		'Puno',
		'Pusi',
		'Putina',
		'Quiaca',
		'Quilcapuncu',
		'Rosaspata',
		'Samán',
		'San Antón',
		'San Antonio',
		'San Gabán',
		'San José',
		'San Juan de Salinas',
		'San Juan del Oro',
		'San Miguel',
		'San Pedro de Putina Punco',
		'Sandia',
		'Santa Lucía',
		'Santa Rosa',
		'Santa Rosa',
		'Santiago de Pupuja',
		'Sina',
		'Taraco',
		'Tilali',
		'Tinicachi',
		'Tiquillaca',
		'Tirapata',
		'Umachiri',
		'Unicachi',
		'Usicayos',
		'Vilavila',
		'Vilque Chico',
		'Vilque',
		'Yanahuaya',
		'Yunguyo',
		'Zepita'
	),
	'SAM' => array(
		'Agua Blanca',
		'Alberto Leveau',
		'Alonso de Alvarado',
		'Alto Biavo',
		'Alto Saposoa',
		'Awajún',
		'Bajo Biavo',
		'Barranquita',
		'Bellavista',
		'Buenos Aires',
		'Cacatachi',
		'Calzada',
		'Campanilla',
		'Caspisapa',
		'Caynarachi',
		'Chazuta',
		'Chipurana',
		'Cuñumbuqui',
		'El Eslabón',
		'El Porvenir',
		'Elías Soplín Vargas',
		'Habana',
		'Huallaga',
		'Huicungo',
		'Huimbayoc',
		'Jepelacio',
		'Juan Guerra',
		'Juanjuí',
		'La Banda de Shilcayo',
		'Lamas',
		'Morales',
		'Moyobamba',
		'Nueva Cajamarca',
		'Nuevo Progreso',
		'Pachiza',
		'Pajarillo',
		'Papaplaya',
		'Pardo Miguel',
		'Picota',
		'Pilluana',
		'Pinto Recodo',
		'Piscoyacu',
		'Pólvora',
		'Posic',
		'Pucacaca',
		'Rioja',
		'Rumisapa',
		'Sacanche',
		'San Antonio',
		'San Cristóbal',
		'San Fernando',
		'San Hilarión',
		'San José de Sisa',
		'San Martín',
		'San Pablo',
		'San Rafael',
		'San Roque de Cumbaza',
		'Santa Rosa',
		'Saposoa',
		'Sauce',
		'Shamboyacu',
		'Shanao',
		'Shapaja',
		'Shatoja',
		'Shunte',
		'Soritor',
		'Tabalosos',
		'Tarapoto',
		'Tingo de Ponasa',
		'Tingo de Saposoa',
		'Tocache',
		'Tres Unidos',
		'Uchiza',
		'Yantalo',
		'Yorongos',
		'Yuracyacu',
		'Zapatero'
	),
	'TAC' => array(
		'Alto de la Alianza',
		'Cairani',
		'Calana',
		'Camilaca',
		'Candarave',
		'Ciudad Nueva',
		'Coronel Gregorio Albarracín Lanchipa',
		'Curibaya',
		'Estique Pampa',
		'Estique',
		'Héroes Albarracín',
		'Huanuara',
		'Ilabaya',
		'Inclán',
		'Ite',
		'La Yarada - Los Palos',
		'Locumba',
		'Pachía',
		'Palca',
		'Pocollay',
		'Quilahuani',
		'Sama',
		'Sitajara',
		'Susapaya',
		'Tacna',
		'Tarata',
		'Tarucachi',
		'Ticaco'
	),
	'TUM' => array(
		'Aguas Verdes',
		'Canoas de Punta Sal',
		'Casitas',
		'Corrales',
		'La Cruz',
		'Matapalo',
		'Pampas de Hospital',
		'Papayal',
		'San Jacinto',
		'San Juan de la Virgen',
		'Tumbes',
		'Zarumilla',
		'Zorritos'
	),
	'UCA' => array(
		'Alexander von Humboldt',
		'Callería',
		'Campoverde',
		'Curimaná',
		'Iparía',
		'Irázola',
		'Manantay',
		'Masisea',
		'Neshuya',
		'Nueva Requena',
		'Padre Abad',
		'Purús',
		'Raimondi',
		'Sepahua',
		'Tahuanía',
		'Yarinacocha',
		'Yurúa'
	),
	'CAL' => array(
		'Bellavista',
		'Callao',
		'Carmen de La Legua-Reynoso',
		'Islas de San Lorenzo y el Frontón',
		'La Perla',
		'La Punta',
		'Mi Perú (Ventanilla)',
		'Ventanilla'
	)
);